services:
  ftp-server:
    image: mrdxdy/ftp-server:0.1.0
    container_name: ftp-server
    environment:
      - FTP_PASS=123456
      - FTP_USER=user
      - PUBLICHOST=dxdy-laptop
    ports:
      - 20-21:20-21/tcp
      - 40000-40009:40000-40009/tcp
    volumes:
      - ./tmp/data:/home/user
